### ISSUE TITLE
Use of optional sensor and actuator attributes

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#302]
In the description for sensors and actuators we mention that you can specify more detailed information on sensor/actuator:

```
**```sensor```** *[optional]*  
The sensing appliance used to produce the data entry.

**```actuator```** *[optional]*  
The actuating appliance consuming the data entry.
```

I assume the idea is to be able to specify something like:
```
- Raindetection.intensity:
  datatype: uint8
  type: sensor
  unit: percent
  description: Rain intensity. 0 = Dry, No Rain. 100 = Covered.
  sensor: my_rain_sensor_1234
```

As of now we give a warning for the example above as "sensor:" is not considered as a standard attribute. What do we want to do? I see two options:

- Keep it and change tooling so it accepts it
- Consider it obsolete and remove it

https://genivi.github.io/vehicle_signal_specification/rule_set/data_entry/sensor_actuator/
https://github.com/GENIVI/vehicle_signal_specification/blob/master/docs-gen/content/rule_set/data_entry/sensor_actuator.md
