### ISSUE TITLE
Multi-level / Hierarchical meta-data format

### ISSUE THREAD

**Issue by gunnarx** [COVESA/vehicle_signal_specification#313]
Some examples were described on this wiki page that discusses [mapping VSS to Android Automotive properties](https://at.projects.genivi.org/wiki/display/DIRO/VSS+to+AOSP+translation+-+WBS
).

In that page there are two proposals.  One of them shows a single-level metadata (which is what the standard VSS currently have)  e.g.

```
- Vehicle.Chassis.Axle.Row1.Wheel.Right.Tire.Pressure
      aospId: VehicleProperty::TIRE_PRESSURE
      aospArea: VehicleAreaWheel::RIGHT_FRONT
```

Noteworthy here is that metadata names have a naming convention -> in this case the prefix "aosp" on each name, to make sure it is unique, and to show what it relates to.

Further down the page is a multi-level / hierarchical metadata format that would put information under a kind of "heading" or namespace.

```
- Vehicle.Chassis.Axle.Row1.Wheel.Left.Tire.Pressure
      AOSP:
          version: 2.0
          package: android.hardware.automotive.vehicle
          id: VehicleProperty::TIRE_PRESSURE
          area: VehicleAreaWheel::LEFT_FRONT     

      ANY_OTHER_OPERATING_SYSTEM_OR_IPC:
          version: 1.0
          package: com.oem.foo
          other_data_for_translation: true
```

In this case, since it is namespaced, the metadata items can have simpler names and still not collide with other usages.

The question therefore is:  Should we recommend, and should the tools support, the use  of this hierarchical method for metadata or should the VSS model require all metadata to be on the toplevel only.  Note that this is a policy decision that affects the standard VSS catalog of data, but also rules/recommendation for any other data defined in proprietary catalogs or layers.
