### ISSUE TITLE
Use of VersionVSS: branch in tagged releases

### ISSUE THREAD

**Issue by slawr** [COVESA/vehicle_signal_specification#343]
Hi,

Looking recently into the code I noticed that the values of the [VersionVSS](https://github.com/GENIVI/vehicle_signal_specification/blob/bcb53893dcff5990d4735168b8966b62d927d2ac/spec/Vehicle/Vehicle.vspec#L18) branch attributes were not set in tagged releases. With the exception of the end user focused 'VersionVSS.Label' attribute, I thought the other attributes were intended to reflect the VSS version - possibly even be fixed.

This is probably a learning moment for me, but wouldn't you expect the tagged releases to have those values set? In the Vehicle.vspec or the serialisation rendering of the data description. That's not the case in the VSS v2.x releases I looked at.

e.g. VSS v2.1 using 'default':
```
VersionVSS.Major:
  datatype: uint32
  type: attribute
  description: Supported Version of VSS - Major version
  default: 2

VersionVSS.Minor:
  datatype: uint32
  type: attribute
  description: Supported Version of VSS - Minor version
  default: 1
```

or 'min':
```
VersionVSS.Major:
  datatype: uint32
  type: attribute
  description: Supported Version of VSS - Major version
  min: 2

VersionVSS.Minor:
  datatype: uint32
  type: attribute
  description: Supported Version of VSS - Minor version
  min: 1
```
