### ISSUE TITLE
Ambiguous *Time signals in Vehicle.vspec

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#356]
The `Vehicle.vspec` file contains four signals that are not well defined. It should better be discussed if they are useful. if they are found to be not useful they could be removed. If they are useful they should preferably get better descriptions, possibly related to the change in #348

- IgnitionOnTime
- IgnitionOffTime
- DriveTime
- IdleTime

Problems/Ambiguities identified so far:

- The description talks about "accumulated" but it is not clear when the value shall be reset. Shall they never be reset, i.e. represent total time during the lifetime of the vehicle, or should they be reset at some time, e.g. when the engine is replaced, by request of the driver or by some other event?
- What is the definition of IgnitionOn?` LowVoltageSystemState in ["ON", "START"]`?
- What is the definition of IgnitionOff?` LowVoltageSystemState in ["LOCK", "OFF","ACC"]`?
- What is the definition of DriveTime?` (LowVoltageSystemState in ["ON", "START"]) AND (Transmission.CurrentGear != 0)`?
- What is the definition of IdleTime?` (LowVoltageSystemState in ["ON", "START"]) AND (Transmission.CurrentGear == 0)`?

**Comment by danielwilms** [comment]
@danielwilms, @adobekan, check internally.
@tguild: using it internally

**Comment by erikbosch** [comment]
@tguild - you mentioned that you use something internally for "engine hours". Do you have the definition on how it is calculated.

After some quick googling it appears that "engine hours" in US seems to include idling. So it is based on whether the engine is rotating or not? I.e. if there is a start-stop system so the engine stops at a traffic light, should then the "hour counter" also stop? And what (if any) is the definition for electrical trucks like the Tesla Cybertruck?  And should the "hour counter" be reset/changed if the engine is replaced, i.e. follow the engine rather than the vehicle?

If it is engine-specific and only defined for combustion engines then maybe a new signal in "CombustionEngine" would be a better alternative, maybe something like below:

```
Vehicle.Powertrain.CombustionEngine.EngineTime:
  datatype: uint32
  type: sensor
  description: Accumulated time during engine lifetime with "engine speed (rpm) > 0".
  unit: s

# Or using hours and float...

Vehicle.Powertrain.CombustionEngine.EngineHours:
  datatype: float
  type: sensor
  description: Accumulated time during engine lifetime with "engine speed (rpm) > 0".
  unit: h
```




"Vehicle.Powertrain.CombustionEngine.Engine.Speed" > 0

**Comment by erikbosch** [comment]
Some Trucks seems to record "IdleTime" for engine as well, but there does not seem to be any standardized definition. According to https://www.thetruckersreport.com/truckingindustryforum/threads/how-are-engine-idle-hours-logged-in-the-ecm-on-the-truck.1346250/ it is sometimes based on engine speed (rpm), e.g. any speed higher than 0 rpm but lower than 700 rpm might be considered as "idle time".

I have no problems having an "IdleTime" or "IdleHours" signal even if there is no standardized definition of "idle time". As long as we clearly state that the vehicle/OEM may use whatever definition/algorithm they want I am fine. 

```
# OEMs may collect statistics on accumulated idle time for an engine
# The definition of when an engine is considered to be idling is not standardized
# It might be based on engine speed (rpm) below a certain limit or any other mechanism 
Vehicle.Powertrain.CombustionEngine.IdleTime:
  datatype: uint32
  type: sensor
  description: Accumulated time during engine lifetime with engine idling.
  unit: s
```
