### ISSUE TITLE
Wheel.Speed

### ISSUE THREAD

**Issue by jdacoello** [COVESA/vehicle_signal_specification#368]
Can you add to the specification the speed property of a wheel? Look, for example, real data sets like [comma2k19 ](https://github.com/commaai/comma2k19) which have this data for all the wheels {front left, front right, rear left, rear right}

**Comment by danielwilms** [comment]
@jdacoello, sure it's possible if there is a use case for it (dataset proves that there is :)). Do you want to create a PR, then we can discuss it there.

**Comment by erikbosch** [comment]
Would fit quite well to `Wheel.vspec`, possibly something like below

```
Speed:
  datatype: float
  type: sensor
  unit: km/h
  description: Vehicle speed calculated from wheel rotation.

```
That would give us 4 new signals when expanded:

```
Vehicle.Chassis.Axle.Row1.Wheel.Left.Speed
Vehicle.Chassis.Axle.Row1.Wheel.Right.Speed
Vehicle.Chassis.Axle.Row2.Wheel.Left.Speed
Vehicle.Chassis.Axle.Row2.Wheel.Right.Speed
```
