### ISSUE TITLE
Feature request: support strings in the list of suffixes in an instance definition

### ISSUE THREAD

**Issue by slawr** [COVESA/vehicle_signal_specification#375]
The VSS v2.2 data model rules support instances using numerical suffixes.
For example:
```
Door:
  type: branch
  instances:
    - Row[1,4]
```
    
producing:
```
Row1.
Row2.
Row3.
Row4.    
```

The request is to extend the rules to allow a list of strings to be used as the suffix.
For example:
```
Door:
  type: branch
  instances:
    - Front["Left", "Right"]
    - Rear["Left", "Right"]
```
would result in:
```
Door.FrontLeft.
Door.FrontRight.
Door.RearLeft.
Door.RearRight.
```

**Comment by erikbosch** [comment]
For the sake of completeness, we already support enums like this:

```
Door:
  type: branch
  instances:
    - ["Front","Rear"]
    - ["Left","Right"]
  description: All doors, including windows and switches
```

Will give you signals like:

```
Vehicle.Cabin.Door.Front.Left.Window.ChildLock
Vehicle.Cabin.Door.Front.Right.Window.ChildLock
Vehicle.Cabin.Door.Rear.Left.Window.ChildLock
Vehicle.Cabin.Door.Rear.Right.Window.ChildLock
```

But we do not support prefix in combination with enum, like this:
```
Door:
  type: branch
  instances:
    - ["Front", "Rear"]
    - Pos["Left", "Right"]

```

I assume it should be quite easy to change tooling so that the prefix (if any) is considered and correctly handled.
