### ISSUE TITLE
ChargingPort / ChargePlugType signals

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#376]
I noticed that we have two signals related to charging port/plug. They should preferably be merged to a single signal, I see no value in keeping both. But what types (enum-literals) do we actually want to have? It seems that IEC 62106 standardizes plugs, but are literals standardized somewhere?

If one compare with Android it seems that we miss IEC Type 3 (deprecated so maybe does not matter that much) and some Tesla variants. Any reason not to have the same (number of) enums as Android?

```
Vehicle.Body.ChargingPort.Type:
  datatype: string
  type: attribute
  enum: [ "unknown", "Not_Fitted", "AC_Type_1", "AC_Type_2", "AC_GBT", "AC_DC_Type_1_Combo", "AC_DC_Type_2_Combo", "DC_GBT", "DC_Chademo" ]
  default: "unknown"
  description: Indicates the primary charging type fitted to the vehicle

Vehicle.Powertrain.TractionBattery.Charging.ChargePlugType:
  datatype: string
  type: attribute
  default: ccs
  enum: [ 'type 1', 'type 2', 'ccs', 'chademo' ]
  description: Type of charge plug available on the vehicle (CSS includes Type2).
```

Android definitions:
(from https://android.googlesource.com/platform/hardware/interfaces/+/master/automotive/vehicle/2.0/types.hal)
```
enum EvConnectorType : int32_t {
    /**
     * Default type if the vehicle does not know or report the EV connector
     * type.
     */
    UNKNOWN = 0,
    IEC_TYPE_1_AC = 1,              // aka Yazaki
    IEC_TYPE_2_AC = 2,              // aka Mennekes
    IEC_TYPE_3_AC = 3,              // aka Scame
    IEC_TYPE_4_DC = 4,              // aka CHAdeMO
    IEC_TYPE_1_CCS_DC = 5,          // aka Combo 1
    IEC_TYPE_2_CCS_DC = 6,          // aka Combo 2
    TESLA_ROADSTER = 7,
    TESLA_HPWC = 8,
    TESLA_SUPERCHARGER = 9,
    GBT_AC = 10,
    GBT_DC = 11,
    /**
     * Connector type to use when no other types apply. Before using this
     * value, work with Google to see if the EvConnectorType enum can be
     * extended with an appropriate value.
     */
    OTHER = 101,
};
```
