### ISSUE TITLE
Use of "default" for attributes/sensors/actuators/enums

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#377]
As of today `default` is only allowed for attributes. The original VSS intention with default as I understand it was for attributes only, so that the "vehicle data broker" (or whatever we like to call it) would get a value for the attribute already when parsing/importing the VSS, so that no other entity/producer in the vehicle needs to provide that value to the "vehicle data broker" . 

In the VSS Slack channel it has been discussed it it would be relevant to make `default`mandatory for all enum-entities in VSS, i.e. also sensors and actuators. Background is that it is quite common in other contexts that enums must have an explicit/implicit default value.

Topics to discuss:

- Do we want to allow `default`also for sensors and actuators?
- If so only for "enum"-types, or also for integer/float types?
- Do we want to make `default` mandatory for enums?

If we want to make `default` mandatory for all enums (also sensors/actuators) we should in my view first agree on what that means. If we take the actuator below as example. Assume an app wants to read or subscribe to `HMI.DistanceUnit` and the vehicle has just restarted so that the "vehicle Data Broker" is up and running, but the HMI has not yet published any value for `DistanceUnit`. What should then be returned? I assume specifying "km" or "mi" as default could give problems, as the app then first might get "km" (default) and then a few seconds later "mi" when HMI has reported the real value. If we want to make default mandatory for all VSS enums we might consider if the default value for signals/actuators should correspond to undefined/unknown. That would allow for apps to ignore observations reporting the default value.  

Current signal:

```
HMI.DistanceUnit:
  datatype: string
  type: actuator
  enum: [ "mi", "km" ]
  description: Distance unit used in the current HMI
```

Possible refactoring to include default and unknown:

```
HMI.DistanceUnit:
  datatype: string
  type: actuator
  enum: [ "unknown", "mi", "km" ]
  default: "unknown"
  description: Distance unit used in the current HMI
```
