### ISSUE TITLE
FuelType signals

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#423]
I noticed that we have two signals concerning fuel type in VSS.  In addition to that they are quite overlapping there are also gaps that they cannot represent, like what types of gasoline it support (e.g. 95 vs 98 RON, E5 vs E10), what type of diesel (e.g. B20 vs B100), or if it is a flexifuel vehicle supporting e.g. both gasoline and E85. Similar for HYBRID it does not say what type of hybrid it is, e.g. if it use gasoline or diesel.

**Current signals**

CombustionEngine.vspec:

```
FuelType:
  datatype: string
  type: attribute
  allowed: ['UNKNOWN', 'GASOLINE', 'DIESEL', 'E85', 'CNG']
  default: 'UNKNOWN'
  description: Type of fuel that the engine runs on.
```

FuelSystem.vspec:

```
FuelType:
  datatype: string
  type: attribute
  allowed: ['UNKNOWN', 'GASOLINE', 'DIESEL', 'ELECTRIC', 'HYBRID', 'E85', 'CNG', 'LPG']
  default: 'UNKNOWN'
  description: Defines the fuel type of the vehicle.

```

**Possible Improvement**

One idea could be to restructure this like below. On top level one signal that describes what type of powertrain a vehicle has. The could be used to make assumptions on what other signals the vehicle will have. For example, if the vehicle is `HYBRID` or `ELECTRIC` then it is likely that signals in `Vehicle.Powertrain.ElectricMotor` and `Vehicle.Powertrain.TractionBattery`will be present, if the vehicle is `HYBRID` or `COMBUSTION` then it is likely that signals in `Vehicle.Powertrain.FuelSystem` and `Vehicle.Powertrain.CombustionEngine` will be present.

```
Powertrain.Type:
  datatype: string
  type: attribute
  allowed: ['COMBUSTION', 'HYBRID', 'ELECTRIC']
  description: Defines the powertrain type of the vehicle.
```
Then for combustion engines 1 or 2 signals of array type could specify what fuel the engine system accepts. Possibly two signals would be useful, one for "high level" information, and another specifying more details on exactly what types that are supported. I do not know if there are any good standard we can use as base. Having an array type means that several fuels can be specified.
```
FuelSystem.SupportedFuelTypes:
  datatype: string[]
  type: attribute
  allowed: ['GASOLINE', 'DIESEL', 'E85', 'CNG', 'LPG', 'OTHER']
  description: High level information of fuel types supported

FuelSystem.SupportedFuel:
  datatype: string[]
  type: attribute
  allowed: ['SP95_E5', 'SP95_E10', 'SP98_E5', 'B7', 'B20', 'B100', 'E85',  'CNG', 'LPG', 'OTHER']
  description: Detailed information on fuel supported.
```

Thoughts? Ideas?

Comparision - Sensoris (source: https://sensoris.org/wp-content/uploads/sites/21/2021/09/sensoris-specification-v1.2.2-public-1.zip)

![image](https://user-images.githubusercontent.com/30996601/157198778-5b804edc-f664-4fc5-8dcc-847fcd9f8768.png)

Comparison: Android HAL: https://android.googlesource.com/platform/hardware/interfaces/+/master/automotive/vehicle/2.0/types.hal#3557

```
    /**
     * List of fuels the vehicle may use
     *
     * @change_mode VehiclePropertyChangeMode:STATIC
     * @access VehiclePropertyAccess:READ
     * @data_enum FuelType
     */
    INFO_FUEL_TYPE = (
        0x0105
        | VehiclePropertyGroup:SYSTEM
        | VehiclePropertyType:INT32_VEC
        | VehicleArea:GLOBAL),

enum FuelType : int32_t {
    /**
     * Fuel type to use if the HU does not know on which types of fuel the vehicle
     * runs. The use of this value is generally discouraged outside of aftermarket units.
     */
    FUEL_TYPE_UNKNOWN = 0,
    /** Unleaded gasoline */
    FUEL_TYPE_UNLEADED = 1,
    /** Leaded gasoline */
    FUEL_TYPE_LEADED = 2,
    /** Diesel #1 */
    FUEL_TYPE_DIESEL_1 = 3,
    /** Diesel #2 */
    FUEL_TYPE_DIESEL_2 = 4,
    /** Biodiesel */
    FUEL_TYPE_BIODIESEL = 5,
    /** 85% ethanol/gasoline blend */
    FUEL_TYPE_E85 = 6,
    /** Liquified petroleum gas */
    FUEL_TYPE_LPG = 7,
    /** Compressed natural gas */
    FUEL_TYPE_CNG = 8,
    /** Liquified natural gas */
    FUEL_TYPE_LNG = 9,
    /** Electric */
    FUEL_TYPE_ELECTRIC = 10,
    /** Hydrogen fuel cell */
    FUEL_TYPE_HYDROGEN = 11,
    /**
     * Fuel type to use when no other types apply. Before using this value, work with
     * Google to see if the FuelType enum can be extended with an appropriate value.
     */
    FUEL_TYPE_OTHER = 12,
};
```
