### ISSUE TITLE
Indexes/Position, use as 0 or 1 for first row?

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#424]
As of today, VSS and VSC use different notation for what is the first row. In VSS we typically use 1 (`Row1`) for first row. In VSC we currently use 0 as index for first row in the seat service. This should better be aligned to avoid misunderstandings and implementation errors. I.e. either we shall use 1 for first row in both VSS and VSC, or use 0 in both VSS and VSC.

**Proposed way forward:**

Agree on if we shall use 1 or 0 for first item (for row, pos, axle, ...) in VSS. If we keep 1 propose a change to VSC. If we want to change to 0 update all concerned VSS signals. Document in [VSS style guide](https://github.com/COVESA/vehicle_signal_specification/blob/master/docs-gen/content/rule_set/basics.md) or in [Instance documentation](https://github.com/COVESA/vehicle_signal_specification/blob/master/docs-gen/content/rule_set/instances.md) the preferred numbering in VSS

VSS:

https://github.com/COVESA/vehicle_signal_specification/blob/master/spec/Cabin/Cabin.vspec

```

Seat:
  type: branch
  instances:
    - Row[1,2]
    - Pos[1,3]
  description: All seats.
```

VSC:

https://github.com/COVESA/vehicle_service_catalog/blob/master/comfort-service.yml
```
      #
      # Seat location
      #
      - name: seat_location_t
        description: |
          The location of the seat in the vehicle
        members:
          - name: row
            datatype: uint8
            description: |
              The row, front 0 and +1 toward rear
          - name: index
            datatype: uint8
            description: |
              The index within the row, 0 left most, +1 toward right
```

(FYI:  @magnusfeuer as I think you created the current VSC seat service)
