### ISSUE TITLE
Instance handling of axles/wheels

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#447]
The wheel-representation in VSS as of today (shown below) does not work that well for certain vehicles.

- Two-wheelers (motorbikes) typically do not have `left` and `right` wheel but just a single wheel on each axle.
- Trucks often have twin wheels on some axles, i.e. 4 wheels on some axles. 

```
Axle:
  instances:
    - Row[1,2]
  type: branch
  description: Axle signals

Axle.Wheel:
  instances: ["Left","Right"]
  type: branch
  description: Wheel signals for axle
```

A possible change could be to address wheels similar to seats, i.e. instead of using left/right use positions:

```
Wheel:
  instances:
    - Row[1,2]
    - Pos[1,4]
  type: branch
  description: Wheel signals
```

But if we would do that we would open up for another question - and that is to review of what data we need for each wheel. If we look at https://github.com/COVESA/vehicle_signal_specification/blob/master/spec/Chassis/Wheel.vspec one can identify some areas where a change could be useful:

- `Brake.FluidLevel` is today given on wheel level, but how frequent is it that vehicle have separate brake fluid containers for individual wheels? Could likely be moved to "axle"-level, or a new `BrakeSystem` branch that can have one or more instance, e.g. typically 1 instance for a passenger car and 2 systems for a motorbike.
- `Brake.PadWear` - is today on wheel level, which will not work well if we start supporting twin wheels as they typically share the the same brake disc/drum/pads. I do not know how many vehicles that actually measure individual pad wear, or if they mostly just estimate padwear based on driving pattern. If they estimate padwear then the signal could likely be on axle-level. If measured, do we rather need a branch `BrakeUnit` with row/pos instantiations, i.e an instantiation that does not necessarily needs to be the same as wheel instantiation? One brake unit could then server multiple wheels (typical truck use case), or multiple brake units could serve a single wheel (typical motorbike front wheel use case).
- `Tire.Pressure`  and `Tire.Temperature` are likely to be measured for each wheel individually.

Thoughts?
