### ISSUE TITLE
Multiplicity of Electrical Engines - how to represent in VSS?

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#459]
In VSS we have today a branch `Vehicle.Powertrain.ElectricMotor` for information on electric motor(s) in the vehicle:

```
#
# The electric motor branch used to host the signals and attributes in ElectricMotor.vspec.
#
Vehicle.Powertrain.ElectricMotor:
  type: branch
  description: Electric Motor specific data.

# Include the electric motor vspec file and attach all its signals and attributes under the
# electric motor branch created above.
#include Powertrain/ElectricMotor.vspec Vehicle.Powertrain.ElectricMotor
```

Vehicles with multiple electrical engines are becoming more usual, e.g. one engine for front axle and one engine for rear axle. Getting individual information for each engine is not possible with current VSS, and this is a possible improvement area for VSS.

But how how would that best be handled? Adding just instance information like below (to support a vehicle with separate engines for each wheel) is possibly, but would likely not fit all vehicles. There could e.g. be 4-wheel-drive electrical cars using a single engine and a traditional 4wd transmission.

```
Vehicle.Powertrain.ElectricMotor:
  type: branch
  description: Electric Motor specific data.
  instances:
    - ["Front","Rear"]
    - ["Left","Right"]
```
Is this possibly a use case for overlays/extensions. E.g. to keeping current (single engine) specification, and adding an overlay adding the part below to change to use two engines instead of one? Or do we see a better solution to support both vehicles with a single engine and vehicles with multiple engines?

```
  instances:
    - ["Front","Rear"]
```

**Comment by danielwilms** [comment]
Discussion:
- maybe remove all instances from standard catalog and add standard profile overlay

**Comment by CorvetteCole** [comment]
I think this seems like a place for overlays, but I agree it is an increasingly important feature (one needed for a car I am working on)

**Comment by erikbosch** [comment]
We regularly close old issues and pull requests that appear to be abandoned or completed, where there have not been any activity for a long time. If you think your item is still relevant please feel to add a comment and re-open it. You are also very welcome to bring up the topic at one of our weekly VSS meetings.

**Comment by yf6** [comment]
I'd like to reopen this issue for consideration, it would be great to be able to represent multiple electric motors.

**Comment by erikbosch** [comment]
Reopened on request by @yf6

**Comment by erikbosch** [comment]
Note that representation has recently changed to be able to handle multiple engines, see https://github.com/COVESA/vehicle_signal_specification/blob/df0fd0472d23bb4b7abaf1b14e20a853d801767e/spec/VehicleSignalSpecification.vspec#L66

But there are some discussion on how to represent instances, current code use labels, some may however prefer numeric instances.

```

Vehicle.Powertrain.ElectricMotor:
  type: branch
  instances: ["Front","Rear","FrontLeft","FrontRight","RearLeft","RearRight"]
  description: Electric Motor specific data.
  comment: Instance Front to be used if the vehicle has a motor located at the front of the vehicle, serving front and possibly also rear axle.
           Instance Rear to be used if the vehicle has a motor located at the rear of the vehicle, serving rear and possiblsy also front axle.
           Instances with Left/Right intended to be used if vehicle has separate motors for left and right side.
```
