### ISSUE TITLE
Definition of "current trip"

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#505]
We have some signals related to "current trip" in VSS, but they do not really give any definition on what is meant with "current trip". Do we consider "current trip" to be something that is manually controlled by the driver (or a vehicle app, like automatic reset when a new rental period begins), i.e. there is no definition that say that starting the engine means that a new trip automatically begins?

A side topic - how does OEMs typically calculate average speed for "current trip". Do they consider all time when "Vehicle.LowVoltageSystemState" is on, i.e. considering time when engine is idling? Or do they exclude time when transmission is in neutral? 

```

ConsumptionSinceStart:
  datatype: float
  type: sensor
  unit: l
  description: Fuel amount in liters consumed since start of current trip.

TimeSinceStart:
  datatype: uint32
  type: sensor
  unit: s
  description: Time in seconds elapsed since start of current trip.


TripMeterReading:
  datatype: float
  type: sensor
  unit: km
  description: Current trip meter reading.


AverageSpeed:
  datatype: float
  type: sensor
  unit: km/h
  description: Average speed for the current trip.

```
