### ISSUE TITLE
How to document intended signal dependency

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#522]
I have noticed a trend in VSS to introduce more "advanced" signals, where the rationale for them might be difficult to understand if you look at them one by one as they are part of a bigger concept. An existing example is the [wiper system](https://github.com/COVESA/vehicle_signal_specification/blob/master/spec/Body/WiperSystem.vspec), an upcoming example is [power optimization](https://github.com/COVESA/vehicle_signal_specification/pull/520).

So far in VSS we have description/comment on individual signals, and sometimes unstructured comments (like `# Bla bla bla`) covering a set of signals. The problem with the unstructured comments are that they are lost when vspecs are transformed to other formats. I think it would be good to align on how to document concepts and design decisions for the catalog. Just using comments in *.vspec files may not be sufficient.

One idea could be to create a "Concepts and Design Decisions" section in the documentation ([source](https://github.com/COVESA/vehicle_signal_specification/tree/master/docs-gen), [generated](https://covesa.github.io/vehicle_signal_specification/)), and create pages there when necessary for understanding.

For instance, maybe writing something like this for power optimize:

**Power Optimize**

The power optimize concept is based on the assumption that the vehicle for a certain set of features has two signals, one representing the preferred value during normal conditions (`A`) and one representing the preferred value during power optimize (`B`). The driver may have the possibility to configure both `A` and `B`. When Power Optimize is ordered by setting `Vehicle.PowerOptimize==True` users (subsystems/ECUs) shall use the value of `B` rather than `A`.

And referencing it in the vspec:

```
PowerOptimize.DisplayBrightnessLevel:
  datatype: float
  type: actuator
  unit: percent
  min: 0
  max: 100
  description: Display BrightnessLevel in the case of PowerOptimize
               0 = Lowest brightness possible.
               100 = Maximum Brightness possible.
  comment: See https://covesa.github.io/vehicle_signal_specification/PowerOptimize.html for intended usage
```
