### ISSUE TITLE
Improve specification of InteriorLights

### ISSUE THREAD

**Issue by jdacoello** [COVESA/vehicle_signal_specification#531]
### LightIntensity as actuator
In [vehicle_signal_specification/spec/Cabin/InteriorLights.vspec](https://github.com/COVESA/vehicle_signal_specification/blob/d5b0c2173e383e3003b54f1a4bc4075988ee7d53/spec/Cabin/InteriorLights.vspec), `LightIntensity` is defined as `sensor`. Should it not be an `actuator` instead?

```
LightIntensity:
  datatype: uint8
  type: sensor
  unit: percent
  min: 0
  max: 100
  description: Intensity of the interior lights. 0 = Off. 100 = Full brightness.
```

### Lights individually controlable
Right now the intensity is referring to all the interior lights. 

### Adding other aspects
For example:
- Color for each light
- Flex (decorative) lights
