### ISSUE TITLE
Comments are not shown in the resulting specification 

### ISSUE THREAD

**Issue by jdacoello** [COVESA/vehicle_signal_specification#539]
I realized that the comments added in the `vspec` files are not part of the resulting specification files produced by the `vss-tools`. Is this a design decision, or do the tools need an update? See an example below:

### Model
```
PerceivedAmbientLight:
  datatype: uint8
  type: sensor
  unit: percent
  min: 0
  max: 100
  description: The percentage of ambient light that is measured (e.g., by a sensor) inside the cabin. 0 = No ambient light. 100 = Full brightness.
  comment: See also Vehicle.Cabin.Lights.AmbientLight, which is used for acting on the decorative coloured lights available in the cabin.
```

### Resulting specification
```
Vehicle.Cabin.Lights.PerceivedAmbientLight:
  datatype: uint8
  description: The percentage of ambient light that is measured (e.g., by a sensor) inside the cabin. 0 = No ambient light. 100 = Full brightness.
  max: 100
  min: 0
  type: sensor
  unit: percent
  uuid: fc0b26067ecc589291c3e5264551bfb4
```
