### ISSUE TITLE
Wrong types defined in OBD.vspec

### ISSUE THREAD

**Issue by jdacoello** [COVESA/vehicle_signal_specification#544]
Some corrections are needed for the types defined in [OBD.vspec](https://github.com/COVESA/vehicle_signal_specification/blob/2b24d0d9ac6b2d357e1d97ca3064cc2ca5bfa089/spec/OBD/OBD.vspec).

For example:

```
FuelType:
  datatype: string
  type: sensor (it should be attribute)
  description: PID 51 - Fuel type
```

```
Status.IgnitionType:
  datatype: string
  type: sensor (it should be attribute)
  allowed: ['SPARK', 'COMPRESSION']
  description: Type of the ignition for ICE - spark = spark plug ignition, compression = self-igniting (Diesel engines)
```

BTW, what is the take on OBD data described in VSS? Is this actually used?
