### ISSUE TITLE
Limit the number of characters with string datatype

### ISSUE THREAD

**Issue by jdacoello** [COVESA/vehicle_signal_specification#545]
### Discussed in https://github.com/COVESA/vehicle_signal_specification/discussions/533

<div type='discussions-op-text'>

<sup>Originally posted by **jdacoello** February 10, 2023</sup>
Is it possible to define the number of valid characters when using string datatype? One example would be to set light colours using hexadecimal color code, where 7 characters are expected.

* `#ABCDEF`

If not, I can create an issue to work on that.</div>

Another example where this function can help is the `VIN` number:

```
VehicleIdentification.VIN:
  datatype: string
  type: attribute
  description: 17-character Vehicle Identification Number (VIN) as defined by ISO 3779.
```

In practice, how do you enforce the use of 17 characters? If this characteristic is only mentioned in the description, one must have a custom function that does the job. In contrast, if a field in VSS explains the constraints, the user can refer to the described constraints.
