### ISSUE TITLE
Case-sensitivity of VSS (type)

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#562]
I noticed that there is a slight contradiction between this repository and vss-tools.

- In VSS documentation, it is implicitly stated that type is mandatory as it is not marked as optional. We do not explicitly state anything on case sensitivity, but the list of values use lower case.
- In VSS-tools we actually use "branch" if type is not specified, and we accept any case and convert it to wanted case

I do not really see any point in the vss-tools handling, so I would like to know if your share my view that type shall be mandatory and must be lower case. If so, we could do 4 things:

- Improve documentation to make it more explicit
- Change some existing signals that use other case, like the one below with `Actuator`
- Then refactor vss-tools so that it does not add type by default. This is actually already covered by https://github.com/COVESA/vss-tools/pull/252
- Refactor vss-tools so that it handle types as case-sensitive.

```
Charging.IsChargingCableLocked:
  datatype: boolean
  type: Actuator
  description: Is charging cable locked to prevent removal.
  comment: Locking of charging cable can be used to prevent unintentional removing during charging.
```
