### ISSUE TITLE
Negative values for combustion engine torque

### ISSUE THREAD

**Issue by ppb2020** [COVESA/vehicle_signal_specification#574]
The current definition of combustion engine torque is as follows:

```
#
# Current Torque
#
Torque:
  datatype: uint16
  type: sensor
  unit: Nm
  description: Current engine torque. Shall be reported as 0 during engine breaking.
  comment: During engine breaking the engine delivers a negative torque to the transmission.
           This negative torque shall be ignored, instead 0 shall be reported.
```

It's not clear why a negative value must be ignored. There are situations where the value of negative torque would be useful in some calculations.

Could the datatype be changed to an int16 in order to support negative values? (V4 being a new major versions, it would be the right time for this kind of change.)
