### ISSUE TITLE
Depressed PedalPosition

### ISSUE THREAD

**Issue by mikehaller** [COVESA/vehicle_signal_specification#626]
`Vehicle.Chassis.Chassis.Accelerator.PedalPosition` is currently described as:

```
Accelerator.PedalPosition:
  datatype: uint8
  type: sensor
  min: 0
  max: 100
  unit: percent
  description: Accelerator pedal position as percent. 0 = Not depressed. 100 = Fully depressed.
```

Using the term `depressed` is probably a mistranslation: `gedrückt` (pushed) or `bedrückt` (depressed) in German

The description should read:

```
Accelerator pedal position as percent. 0 = Released. 100 = Fully pushed down.
```

References:
<https://github.com/COVESA/vehicle_signal_specification/blob/9481aef876f117f3cdec2eba867fbd43f27060b6/spec/Chassis/Chassis.vspec#L183>
