### ISSUE TITLE
Question: Is there a standard signal serialization format?

### ISSUE THREAD

**Issue by sophokles73** [COVESA/vehicle_signal_specification#627]
I was wondering if there is a standard mechanism/format for serializing VSS data to a byte array/stream.
This could be used to transfer signal data from a vehicle to a back end application using e.g. MQTT and or HTTP.
Ideally, such a format would not be overly verbose. In particular, the VSS data entry names like `Vehicle.Powertrain.CombustionEngine.DieselExhaustFluid.Level` could increase the payload size dramatically, so some form of meta data based serialization like protobuf comes to mind. However, I haven't (yet) found a corresponding protobuf definition, or am I mistaken?

**Comment by sophokles73** [comment]
Thank you for the pointer, @erikbosch 

My understanding of the `vspec2protobuf.py` script is that it simply iterates over the Data Entry definitions and creates corresponding protobuf Message definitions. I am a little concerned regarding backwards compatibility when e.g. a new minor version of VSS is being released which maybe changes the ordering of the Data Entry defs and/or introduces new entries. My current feeling is that it will not necessarily be possible to use the resulting proto file to de-serialize a protobuf message that had been created using the original protobuf definition because of the property identifiers being shuffled, overridden etc.

FMPOV it would be helpful to introduce a fixed identifier for the VSS Data Entries which remain constant over time and cannot be reused. You mentioned the use of UUIDs being discussed for that matter. That could be one way of doing it. Another option with a smaller footprint might be to use a similar scheme like the one being used in e.g. SMNP, where you assign a simple integer (counting from 1 up) to each node/leaf in the tree. This identifier could then be used as the property IDs in the protbof Message definitions and could also be used as a more compact identifier in other serialization formats.

**Comment by erikbosch** [comment]
@adobekan - what is the status of your ideas to refactor UUID handling? Is it it still just a thought - it seems to be related to the comment from Kai above

**Comment by adobekan** [comment]
proto could be used but problem would be, how do you exchange and manage schema between integration points. What we were thinking is something related to what @sophokles73 is mentioning.  It was related to short UUID element, e.g. 3 bytes (1byte for version/layers/source, e.g. what is public vs private) (2bytes for fixed id of each element, which stays with leaf after creation)

@erikbosch  Still on my ToDo list, soon we will start working on this.

**Comment by sophokles73** [comment]
Here's an example of what I have in mind:
```
#
# The vehicle branch for highlevel vehicle signals and attributes.
#
Vehicle:
  type: branch
  id: 1
  description: High-level vehicle data.

# Include the Vehicle/Vehicle.vspec file and attach all its signals under the
# Vehicle branch created above.

#include Vehicle/Vehicle.vspec Vehicle
```
Now define the VehicleIdentification subtree
```
VehicleIdentification:
  type: branch
  id: 1
  description: Attributes that identify a vehicle.

VehicleIdentification.VIN:
  datatype: string
  type: attribute
  id: 1
  description: 17-character Vehicle Identification Number (VIN) as defined by ISO 3779.

VehicleIdentification.WMI:
  datatype: string
  type: attribute
  id: 2
  description: 3-character World Manufacturer Identification (WMI) as defined by ISO 3780.

VehicleIdentification.Brand:
  datatype: string
  type: attribute
  id: 3
  description: Vehicle brand or manufacturer.

VehicleIdentification.Model:
  datatype: string
  type: attribute
  id: 4
  description: Vehicle model.

VehicleIdentification.Year:
  datatype: uint16
  type: attribute
  id: 5
  description: Model year of the vehicle.
```

Now the  *Vehicle.VehicleIdentification.Year* data entry could also be referred to by `1.1.5` (either as a String or a sequence of uint16).

In a protopuf definition, this could also be used:
```
message Vehicle {
  VehicleVehicleIdentification VehicleIdentification = 1;
  ....
}

message VehicleVehicleIdentification {
  string VIN = 1;
  string WMI = 2;
  string Brand = 3;
  string Model = 4;
  uint32 Year = 5;
  ...
}
```
The IDs used in the message definitions are the values of the corresponding Data Entry definitions' *id* properties. These cannot be changed over time and if a new property is being added, a new *id* value is being defined in the vspec. Similarly, if a property is being removed, its *id* value will not be reused.

This way, it should be quite simple to make sure that protobuf message definitions generated from the vspec files remain backward compatible. The ids could also be used in other serialization formats like JSON in order to increase the payload vs. meta data ratio. It makes a big difference if I use `Vehicle.VehicleIdentification.Year` or just `1.1.5` and if I have a message that contains dozens of data points it adds up quite substantially ...
