### ISSUE TITLE
Does VSS-syntax only support a single root?

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#662]
Today we mention here and there in the documentation that the VSS catalog forms a tree, and vss-tools actually gives an error if you have more than one root. But we do not really say anywhere that a model using VSS-syntax must have a single root, i.e. that something like below is an invalid VSS model. 

If we want to keep the idea that there can only be a single tree and a single root I think we should improve documentation so it clearly states that. If we do not think that is a reasonable limitation we should start looking at how vss-tools can support multiple trees.

(Whether a VSS model must have exactly one root or not does not necessarily affect downstream implementations, as an implementation may support access to multiple models in parallel)

```
a:
  type: branch
  description: Branch A.

a.b:
  datatype: float
  type: sensor
  unit: km
  description: A sensor.
  
c:
  type: branch
  description: Branch A.

c.d:
  datatype: float
  type: sensor
  unit: km
  description: A sensor.
```
