### ISSUE TITLE
Anyone using non-instantiated signal (instantiate: false)

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#666]
The `instantiate: false` attribute is described in VSS documentation but not actively used in current VSS standard catalog. It is intended to give something similar to C++ static class members, but that is not always easy to represent in all target environments/formats, i.e. not necessarily easy to support in all existing or future vss-tools. By that reason I would like to know:

- Is there someone using `instantiate: false` in their own (private) VSS implementation?
- If not, would be a candidate for removal, or alternatively state that it not will be accepted in standard catalog (i.e. error when using `--strict` mode)? 

https://covesa.github.io/vehicle_signal_specification/rule_set/instances/#how-can-i-exclude-child-nodes-from-instantiation

```
# Cabin.vspec
Door:
  type: branch
  instances:
    - Row[1,2]
    - ["DriverSide","PassengerSide"]
  description: All doors, including windows and switches
#include SingleDoor.vspec Door

Door.SomeSignal:
  datatype: uint8
  type: attribute
  instantiate: false
  description: A door signal that should not be instantiated.
```
