### ISSUE TITLE
Securing a consistent use of concepts that derive from other concepts

### ISSUE THREAD

**Issue by jdacoello** [COVESA/vehicle_signal_specification#675]
There are currently situations where a property is modelled (e.g., `Window.Position`). Then another property, that could be easily derived from the previous one, is also defined (e.g., Window.IsOpen)

```YAML
Vehicle.Cabin.Door.Row1.Left.Window.Position:
  datatype: uint8
  description: Window position. 0 = Fully closed 100 = Fully opened.
  max: 100
  min: 0
  type: sensor
  unit: percent
```

```YAML
Vehicle.Cabin.Door.Row1.Left.Window.IsOpen:
  datatype: boolean
  description: Is window open or closed?
  type: sensor
```

Concepts like `Window.IsOpen` can be easily inferred from the `Window.Position`. What is the benefit of modeling multiple concepts that create redundant information? It can also be inconsistent in some cases. For instance, let's assume that `Window.Position` has the value of `50`, but `Window.IsOpen` is `False`. As you can see, they are inconsistent because they contradict each other.
When both are specified, the VSS user would be responsible for applying the necessary logic to validate the data before feeding the actual data to the corresponding topic. 

Any idea how we can add consistency to these cases where basis and derived information is modelled?

I think that a guideline or a ruleset has to be provided because people are often tempted to further specify concepts that can easily be derived from others.
