### ISSUE TITLE
Enforce "style" for VSS standard catalog

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#700]
Now and then the topic on what identifiers that shall be allowed in VSS comes up. As of today we are quite flexible in documentation, we sort of say that as long as it is valid Yaml we support it. This makes however tooling more complex if it is to handle identifiers with odd characters or allowed/default values containing blanks. We do state recommendations in some places like for [allowed values](https://covesa.github.io/vehicle_signal_specification/rule_set/data_entry/allowed/#recommendation-on-string-values) and [node names](https://covesa.github.io/vehicle_signal_specification/rule_set/basics/#naming-conventions) and we have some support in vss-tools to give warnings or even fail if using strict mode.

But we do not enforce strict mode as a criteria for standard catalog, so as of today we have signals like this that does not follow the style guide (Values like "01" are not recommended):

```
PidsA:
  datatype: string[]
  type: attribute
  allowed: ["01","02","03","04","05","06","07","08","09","0A","0B","0C","0D","0E","0F","10","11","12","13","14","15","16","17","18","19","1A","1B","1C","1D","1E","1F","20"]
  description: PID 00 - Array of the supported PIDs 01 to 20 in Hexadecimal.
```

Some ideas:

- Remove the term "recommended" from VSS documentation. Instead separate between what is valid VSS syntax and what is acceptable for VSS standard catalog.
- Require that generic VSS tooling (the tooling that parse vspec files) can handle any VSS syntax
- But for generators/exporters only require that they can handle what is acceptable for VSS standard catalog
- Change Continuous Integration so that we use strict mode and give error if characters/style not allowed in standard catalog is detected.

Example:

_A signal name `Vehicle.Räksmörgås` is valid in VSS as it is a valid Yaml name. VSS-tools generic functionality shall support it. But we should not accept it in standard catalog as it does not follow the rules for the standard catalog. Exporters/Generators does not need to support `Vehicle.Räksmörgås`, but if so they should give an error._

But if we are to change like this we need to change the PId signals as well, but they may anyway be removed by #635
