### ISSUE TITLE
Overlay childrens are not merged causing extensions_attributes missing

### ISSUE THREAD

**Issue by DanielLazarHTDM** [COVESA/vehicle_signal_specification#736]
Currently if my overlay contains following:
```
Vehicle.Cabin.Seat.Row1.DriverSide.Switch.IsForwardEngaged:
   datatype: boolean
   type: actuator
   dbc2vss:
      signal: VCLEFT_SeatDriverSwitchFwEngaged
   vss2dbc:
      signal: VCLEFT_SeatDriverSwitchFwEngaged
   dbc2name:
      name: SeatDemoFrame
```

and I do call:
```
vss-tools/vspec2json.py -e vss2dbc,dbc2vss,dbc2name -o dbc_overlay_seat_demo.vspec -u spec/units.yaml --json-pretty ./spec/VehicleSignalSpecification.vspec vss_dbc.json
```

final json file does not include extended data ```dbc2vss```, ```vss2dbc```, ```dbc2name```.
I assume that this should be considered as bug.

I did research and found root of this problem. In the file:

```
vss-tools/vspec/__init__.py
```

```
diff --git a/vspec/__init__.py b/vspec/__init__.py
index 2bf4de5..18f8d29 100755
--- a/vspec/__init__.py
+++ b/vspec/__init__.py
@@ -456,6 +456,13 @@ def expand_tree_instances(tree: VSSNode):
                     # instead merging it to the new node
                     existing_item.parent = None
                     expand_node.merge(existing_item)
+                    def merge_children(node1, node2):
+                        for c in node1.children:
+                            for cc in node2.children:
+                                if c.name == cc.name:
+                                    c.merge(cc)
+                                    merge_children(c, cc)
+                    merge_children(expand_node, existing_item)
                     break
             expand_node.parent = instantiated_branch
         return instantiated_branc
```

So I've put little recursion to merge also childrens resulting ```extended_attributes``` are correctly copied to final JSON file. Since I don't have deep knowledge about everything how things are generated could someone please validate it ?
