### ISSUE TITLE
Mathematical Operation in Vspec

### ISSUE THREAD

**Issue by sanyakamra** [COVESA/vehicle_signal_specification#738]
- Regarding the specification for Vehicle.Timeincurrentrip, could you please clarify if it's possible to utilize the variables x and y defined in the parameters section to perform a mathematical operation in the transform block to calculate the value of Time in current trip? If so, what specific mathematical operation should be applied using these variables?

- I'm currently exploring the possibility of performing mathematical operations on two signals under a signal math transform. Specifically, I'd like to calculate the average time in the current trip by subtracting the start and stop times. Could you please provide guidance on how I can achieve this within the signal math transform?

**Comment by erikbosch** [comment]
I am not sure if I fully understand the context of the issue. We do not have `Vehicle.Timeincurrentrip` in the standard catalog. We have some trip-related data at https://github.com/COVESA/vehicle_signal_specification/blob/master/spec/Vehicle/Vehicle.vspec#L220

**Comment by sanyakamra** [comment]
Hi @erikbosch,

That is correct. I'm exploring the possibility of implementing mathematical operations on two standard signals to obtain their values when using the 'getValue' function on a third signal.

I've attached the current selected signal below. My question is whether we can perform mathematical operations on two standard signals within the 'math' field of another third signal.

```

Vehicle.Powertrain.TractionBattery.Charging.TimeToComplete:
  type: "sensor"
  datatype: "unin32"
  unit: "s"
  description: "Estimated time to full charge"
  transform:
    math: "((72 * (1 - x)) / ((y * 120) / 1000))"
  parameters:
    x: Vehicle.Powertrain.TractionBattery.StateOfCharge.Current
    y: Vehicle.Powertrain.TractionBattery.Charging.ChargeRate
```
