### ISSUE TITLE
Insurance relevant Parameters

### ISSUE THREAD

**Issue by StefanSellschopp** [COVESA/vehicle_signal_specification#754]
[09072024_Covesa_Allianz_UseCasesADAS_Risk_LiabilityData_Table_V8.xlsx](https://github.com/user-attachments/files/16145449/09072024_Covesa_Allianz_UseCasesADAS_Risk_LiabilityData_Table_V8.xlsx)

the first tab describes relevant data points (AggregationDataPoints),  (the tabs on the right describes specific situations and can be ignored)
the first ones include the VSS parameters I could find in VSS4.2 - any additions?
the lower ones are missing from my perspectives - any thoughts?

**Comment by SebastianSchildt** [comment]
The attached xls has more, but for convencience and a quick glance: 
<img width="680" alt="image" src="https://github.com/user-attachments/assets/f89b445c-0572-419b-9325-9d1969d0c6a3">

<img width="847" alt="image" src="https://github.com/user-attachments/assets/76ea49b9-c2bb-400c-a234-c09a7a5451bf">


<img width="740" alt="image" src="https://github.com/user-attachments/assets/16dcf0ea-0dff-4d11-be97-20436d358729">

**Comment by SebastianSchildt** [comment]
So there is acceleration in Vehicle:

```yaml
Acceleration:
  type: branch
  description: Spatial acceleration. Axis definitions according to ISO 8855.

Acceleration.Longitudinal:
  datatype: float
  type: sensor
  unit: m/s^2
  description: Vehicle acceleration in X (longitudinal acceleration).

Acceleration.Lateral:
  datatype: float
  type: sensor
  unit: m/s^2
  description: Vehicle acceleration in Y (lateral acceleration).

Acceleration.Vertical:
  datatype: float
  type: sensor
  unit: m/s^2
  description: Vehicle acceleration in Z (vertical acceleration).
```

Same for gyroscope:

```
#
# Spatial Rotation
#
AngularVelocity:
  type: branch
  description: Spatial rotation. Axis definitions according to ISO 8855.

AngularVelocity.Roll:
  datatype: float
  type: sensor
  unit: degrees/s
  description: Vehicle rotation rate along X (longitudinal).

AngularVelocity.Pitch:
  datatype: float
  type: sensor
  unit: degrees/s
  description: Vehicle rotation rate along Y (lateral).

AngularVelocity.Yaw:
  datatype: float
  type: sensor
  unit: degrees/s
  description: Vehicle rotation rate along Z (vertical).
```
Basically insurance side there would needed to be the added "non-functional  requirement" for a system to provide this in the desired frequency and range

*Dashcam data*: In VSS we would not "model" video data (as a datatype/stream), but certeinly the existence of a dashcam and a "location" to the ringbuffer may be modelled, see i.e. https://covesa.github.io/vehicle_signal_specification/rule_set/data_entry/data_types/#data-streams



*Pedestrian Protection*:Does this mean some form of pedestrian protection has been deployed, like an airbag? (or this kind of "reactive armor" kind of hoods?), or does this mean existence of some system?

*descent/ascent*: What is meant here? Whether the vehicle is on a slope?

**Comment by SebastianSchildt** [comment]
And Outside AirTemperature is

Vehicle.Exterior

```yaml
AirTemperature:
  datatype: float
  type: sensor
  unit: celsius
  description: Air temperature outside the vehicle.
```
