### ISSUE TITLE
Vss signal not able to map in json

### ISSUE THREAD

**Issue by sanyakamra1996** [COVESA/vehicle_signal_specification#795]
Hi,

I have a signal in VSS:

```
Vehicle.Chassis.Axle.Row1.Wheel.Left.Tire.Pressure:
  datatype: unit16
  type: sensor
  description: Front left tire pressure.
  dbc2vss:
    on_change: true
    signal: TPM_FLR
```
However, when I build VSS, this signal doesn’t show up in the JSON.

Other signals like Vehicle.Body.Trunk.Rear.IsOpen or Vehicle.Cabin.Door.Row1.PassengerSide.IsOpen work fine and display the DBC signal in the JSON.

For the above signal, I even tried using Vehicle.Chassis.Axle.Row1.Wheel.Left.Tire.IsPressureLow, but it still doesn’t appear in the JSON.

The existing JSON seems to include default entries, like this:
```

"Pressure": {
  "datatype": "uint16",
  "description": "Tire pressure in kilo-Pascal.",
  "type": "sensor",
  "unit": "kPa"
}
```
Could you help me understand why the signal isn’t being reflected properly in the JSON?

**Comment by erikbosch** [comment]
Hi!

How did you generate the JSON? I tried:

* Adding an overlay file `overlay.vspec`

```
Vehicle.Chassis.Axle.Row1.Wheel.Left.Tire.Pressure:
  datatype: uint16
  type: sensor
  description: Front left tire pressure.
  dbc2vss:
    on_change: true
    signal: TPM_FLR
```

Then generating JSON using installed vss-tools, the overlay and the extra attribute `dbc2vss`:

`erik@debian6:~/vehicle_signal_specification$ vspec export json --vspec spec/VehicleSignalSpecification.vspec --overlays overlay.vspec --pretty -o hej.json --extended-attributes dbc2vss`

Then looking in the JSON the overlay seem to have been correctly applied.

```
                         "Tire": {
                            "children": {
                              "IsPressureLow": {
                                "datatype": "boolean",
                                "description": "Tire Pressure Status. True = Low tire pressure. False = Good tire pressure.",
                                "type": "sensor"
                              },
                              "Pressure": {
                                "datatype": "uint16",
                                "dbc2vss": {
                                  "on_change": true,
                                  "signal": "TPM_FLR"
                                },
                                "description": "Front left tire pressure.",
                                "type": "sensor",
                                "unit": "kPa"
                              },
                              "Temperature": {
                                "datatype": "float",
                                "description": "Tire temperature in Celsius.",
                                "type": "sensor",
                                "unit": "celsius"
                              }
                            },
                            "description": "Tire signals for wheel.",
                            "type": "branch"
                          }
```
