### ISSUE TITLE
Duplicated name: Axle.Wheel

### ISSUE THREAD

**Issue by jdacoello** [COVESA/vehicle_signal_specification#810]
I will try to implement it then.

BTW, it seems that while this fix was being discussed, the concept `Vehicle.MotionManagement.Brake.Axle.Wheel` was introduced to the spec. Which is again creating the undesired duplicated names:
```
                                            
fqn                                                  
Vehicle.Chassis.Axle.Wheel                 Axle.Wheel
Vehicle.MotionManagement.Brake.Axle.Wheel  Axle.Wheel
```

I will create another issue and suggest the fix for it.

_Originally posted by @jdacoello in https://github.com/COVESA/vehicle_signal_specification/issues/799#issuecomment-2639374645_

**Comment by jdacoello** [comment]
Inside `Vehicle.MotionManagement.Brake.Axle.Wheel`, we have:
```yaml
Torque:
  datatype: int16
  max: 0
  unit: Nm
  type: sensor
  description: Estimated friction brake torque. Brake Torque < 0Nm.

TorqueArbitrated:
  datatype: int16
  max: 0
  unit: Nm
  type: sensor
  description: Brake system internally calculated friction brake torque target. Brake Torque < 0Nm.

TorqueFrictionMaximum:
  type: actuator
  datatype: int16
  max: 0
  unit: Nm
  description: Maximum wheel torque request for friction brake. Brake Torque < 0Nm.

TorqueFrictionMinimum:
  type: actuator
  datatype: int16
  max: 0
  unit: Nm
  description: Minimum wheel torque request for friction brake. Brake Torque < 0Nm.

OmegaUpper:
  type: actuator
  datatype: uint16
  unit: rad/s
  description: Upper wheel speed limit request controlled by friction brake. ISO 8855 wheel-spin velocity.

OmegaLower:
  type: actuator
  datatype: uint16
  unit: rad/s
  description: Lower wheel speed limit request controlled by friction brake. ISO 8855 wheel-spin velocity.
```

Inside `Vehicle.Chassis.Axle.Wheel` we have:
```yaml
Brake:
  type: branch
  description: Brake signals for wheel

Brake.FluidLevel:
  datatype: uint8
  type: sensor
  unit: percent
  max: 100
  description: Brake fluid level as percent. 0 = Empty. 100 = Full.

Brake.IsFluidLevelLow:
  datatype: boolean
  type: sensor
  description: Brake fluid level status. True = Brake fluid level low. False = Brake fluid level OK.

Brake.PadWear:
  datatype: uint8
  type: sensor
  unit: percent
  max: 100
  description: Brake pad wear as percent. 0 = No Wear. 100 = Worn.

Brake.IsBrakesWorn:
  datatype: boolean
  type: sensor
  description: Brake pad wear status. True = Worn. False = Not Worn.


#
# Tire
#
Tire:
  type: branch
  description: Tire signals for wheel.

Tire.Pressure:
  datatype: uint16
  type: sensor
  unit: kPa
  description: Tire pressure in kilo-Pascal.

Tire.IsPressureLow:
  datatype: boolean
  type: sensor
  description: Tire Pressure Status. True = Low tire pressure. False = Good tire pressure.

Tire.Temperature:
  datatype: float
  type: sensor
  unit: celsius
  description: Tire temperature in Celsius.


#
# Wheel signals
#

Speed:
  datatype: float
  type: sensor
  unit: km/h
  description: Linear speed of a vehicle's wheel.

AngularSpeed:
  datatype: float
  type: sensor
  unit: degrees/s
  description: Angular (Rotational) speed of a vehicle's wheel.
  comment: Positive if wheel is trying to drive vehicle forward.
           Negative if wheel is trying to drive vehicle backward.
```

**Comment by erikbosch** [comment]
The challenge as I see it with these signals is that both `Axle` and `Wheel` are instances, so if we are to rename them we need to select something that gives a good meaning, and and the same time avoid to get too long expanded paths. We could for instance say that the branches within MotionManagement concerns dynamics only, and thus rename the branches accordingly. But doing that for all non-unique branches could also for example result in that `Vehicle.MotionManagement.Brake.Axle.Row1.Wheel.Left.Torque` would be replaced by `Vehicle.MotionManagement.BrakeDynamics.AxleDynamics.Row1.WheelDynamics.Left.Torque` which does not really make the name easier to understand. Even if we just would change it on for example axle level it would still result in `Vehicle.MotionManagement.Brake.AxleDynamics.Row1.Wheel.Left.Torque`.

In VSS as of today we do no really separate between "class-name" and "instance-name". Now and then I have thought if we possibly should support another attribute `typename` to be able to use the short name (i.e. `brake`) in getters/setters or a part of the fully qualified name, and type-name when generating for example classes/structs in the target format/language.

```
Brake:
  typename: MotionManagementBrakeInformation
  type: branch
  description: Brake signals for wheel
```
