### ISSUE TITLE
Reuse existing standard vocabulary for units and their conversions

### ISSUE THREAD

**Issue by jdacoello** [COVESA/vehicle_signal_specification#828]
>
- D: 3 action points
- 1. Check how we can reuse existing standards, including conversion, D can investigate

_Originally posted by @erikbosch in https://github.com/COVESA/vehicle_signal_specification/issues/824#issuecomment-2912755968_

Enhance the VSS modeling approach by importing or reusing established standards to avoid re doing it from scratch.

* Would this better fit the `vss-tools` instead?

**Comment by jdacoello** [comment]
Alternatives:
- https://www.qudt.org  --> Most complete option with conversion information
- https://ucum.org
- http://www.ontology-of-units-of-measure.org

**Comment by jdacoello** [comment]
Example on how we could adapt VSS to reuse existing QUDT units.

> Let's say we want to reuse the kilometre `km` from the [reference standard QUDT](https://qudt.org/vocab/unit/KiloM).


## Option 1: Add identifier of QUDT definition to VSS units file

```yaml
km:
  definition: Length measured in kilometers
  unit: kilometer
  quantity: length
  allowed-datatypes: ['numeric']
  unitRef: http://qudt.org/vocab/unit/KiloM  # <--- This is the pointer to the resource
```
This file can also follow the `YAML-LD` approach to write compact pointers by using prefixes.
```yaml
@context:
  qudtUnit: "http://qudt.org/vocab/unit/"
  unitRef: "@id"
km:
  definition: Length measured in kilometers
  unit: kilometer
  quantity: length
  allowed-datatypes: ['numeric']
  unitRef: "qudtUnit:KiloM"  # <--- This is the pointer to the resource
```

## Option 2: Use the URI of the unit directly
```yaml
km: http://qudt.org/vocab/unit/KiloM  # <--- This is the pointer to the resource
```
